#!/usr/bin/env node
/**
 * overhaul-ui — scale
 *
 * Modular type scale + 4px spacing scale, with optional fluid clamp() output.
 *
 *   node scripts/scale.mjs
 *   node scripts/scale.mjs --base=16 --ratio=1.25 --steps=9 --fluid --css
 *   node scripts/scale.mjs --ratio=1.333 --json
 *   node scripts/scale.mjs --tailwind
 *
 * Options
 *   --base=<px>     body size (default 16)
 *   --ratio=<n>     1.125 | 1.2 | 1.25 | 1.333 | 1.414 | 1.5 | 1.618 (default 1.25)
 *   --steps=<n>     steps above base (default 6, max 9)
 *   --down=<n>      steps below base (default 2)
 *   --fluid         emit clamp() for display sizes
 *   --vw-min=<px>   fluid viewport floor (default 360)
 *   --vw-max=<px>   fluid viewport ceiling (default 1440)
 *   --css | --tailwind | --json
 *
 * Every clamp() keeps a rem term in the middle. `clamp(2rem, 5vw, 4rem)` with
 * no rem term ignores user zoom and fails WCAG 1.4.4.
 */

import { parseArgs, c } from './lib/util.mjs';

const args = parseArgs();
const base = num(args.base, 16);
const ratio = num(args.ratio, 1.25);
const up = int(args.steps, 6, 1, 9);
const down = int(args.down, 2, 0, 4);
const fluid = !!args.fluid;
const vwMin = num(args['vw-min'], 360);
const vwMax = num(args['vw-max'], 1440);
const format = args.json ? 'json' : args.tailwind ? 'tailwind' : args.css ? 'css' : 'pretty';

const RATIO_NAMES = {
  1.125: 'major second — very tight, dense dashboards',
  1.2: 'minor third — tight, product UI',
  1.25: 'major third — balanced, the best default',
  1.333: 'perfect fourth — expressive, marketing',
  1.414: 'augmented fourth — dramatic, display-led',
  1.5: 'perfect fifth — very dramatic',
  1.618: 'golden — editorial, few levels only',
};

const NAMES_UP = ['lg', 'xl', '2xl', '3xl', '4xl', '5xl', '6xl', '7xl', '8xl'];
const NAMES_DOWN = ['sm', 'xs', '2xs', '3xs'];

/* -------------------------------------------------------------- type scale */

function buildType() {
  const out = [];
  for (let i = down; i >= 1; i--) {
    out.push({ name: NAMES_DOWN[i - 1], px: round(base / ratio ** i, 2), step: -i });
  }
  out.push({ name: 'base', px: base, step: 0 });
  for (let i = 1; i <= up; i++) {
    out.push({ name: NAMES_UP[i - 1], px: round(base * ratio ** i, 2), step: i });
  }
  return out.map((t) => ({
    ...t,
    rem: round(t.px / 16, 4),
    leading: t.px >= 40 ? 1.05 : t.px >= 28 ? 1.15 : t.px >= 20 ? 1.25 : t.px >= 15 ? 1.55 : 1.45,
    tracking: t.px >= 76 ? '-0.04em' : t.px >= 56 ? '-0.03em' : t.px >= 36 ? '-0.02em' : t.px >= 24 ? '-0.01em' : '0',
    fluid: fluid && t.px >= base * ratio ** 2 ? clamp(t.px) : null,
  }));
}

/**
 * clamp(min, <rem term> + <vw term>, max) — a linear interpolation between
 * two viewport widths, with the rem term preserved for zoom accessibility.
 */
function clamp(maxPx) {
  const minPx = Math.max(base, round(maxPx * 0.62, 2));
  const slope = (maxPx - minPx) / (vwMax - vwMin);
  const interceptPx = minPx - slope * vwMin;
  const vw = round(slope * 100, 3);
  const remTerm = round(interceptPx / 16, 4);
  return `clamp(${round(minPx / 16, 4)}rem, ${remTerm}rem + ${vw}vw, ${round(maxPx / 16, 4)}rem)`;
}

/* ------------------------------------------------------------ space scale */

const SPACE = [0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 20, 24, 32, 40];
function buildSpace() {
  return SPACE.map((n) => ({ name: String(n), px: n * 4, rem: round((n * 4) / 16, 4) }));
}

const type = buildType();
const space = buildSpace();

/* ------------------------------------------------------------------ output */

if (format === 'json') {
  console.log(JSON.stringify({
    tool: 'overhaul-ui/scale',
    base, ratio, ratioName: RATIO_NAMES[ratio] || 'custom',
    type, space,
    guidance: {
      measureProse: '60-75ch',
      measureDisplay: '20-40ch',
      note: 'Body stays fixed; only display sizes go fluid.',
    },
  }, null, 2));
} else if (format === 'css') {
  console.log(cssOut());
} else if (format === 'tailwind') {
  console.log(tailwindOut());
} else {
  pretty();
}

function cssOut() {
  const l = ['/* generated by overhaul-ui scale */', ':root {'];
  l.push(`  /* type — base ${base}px, ratio ${ratio} */`);
  for (const t of type) {
    l.push(`  --text-${t.name}: ${t.rem}rem;${sp(t.name)} /* ${t.px}px */`);
  }
  const display = type.filter((t) => t.fluid);
  if (display.length) {
    l.push('');
    l.push('  /* fluid display sizes — rem term retained for user zoom (WCAG 1.4.4) */');
    for (const t of display) l.push(`  --text-${t.name}-fluid: ${t.fluid};`);
  }
  l.push('');
  l.push('  /* leading */');
  l.push('  --leading-none: 1;');
  l.push('  --leading-tight: 1.1;');
  l.push('  --leading-snug: 1.35;');
  l.push('  --leading-normal: 1.55;');
  l.push('  --leading-relaxed: 1.7;');
  l.push('');
  l.push('  /* tracking */');
  l.push('  --tracking-tighter: -0.04em;');
  l.push('  --tracking-tight: -0.02em;');
  l.push('  --tracking-normal: 0;');
  l.push('  --tracking-wide: 0.08em;');
  l.push('  --tracking-widest: 0.16em;');
  l.push('');
  l.push('  /* space — 4px base */');
  for (const s of space) l.push(`  --space-${s.name}: ${s.rem === 0 ? '0' : `${s.rem}rem`};${sp(s.name)} /* ${s.px}px */`);
  l.push('');
  l.push('  --gutter: clamp(1rem, 4vw, 2.5rem);');
  l.push('  --section-y: clamp(4rem, 8vw, 10rem);');
  l.push('  --measure-prose: 68ch;');
  l.push('  --measure-display: 32ch;');
  l.push('}');
  return l.join('\n');
}

function tailwindOut() {
  const l = ['@import "tailwindcss";', '', '@theme {'];
  for (const t of type) l.push(`  --text-${t.name}: ${t.rem}rem;`);
  for (const t of type.filter((x) => x.fluid)) l.push(`  --text-${t.name}-fluid: ${t.fluid};`);
  l.push('');
  for (const s of space) l.push(`  --spacing-${s.name}: ${s.rem === 0 ? '0' : `${s.rem}rem`};`);
  l.push('}');
  return l.join('\n');
}

function pretty() {
  console.log(`\n${c.bold('overhaul-ui scale')}  ${c.gray(`base ${base}px · ratio ${ratio}`)}`);
  console.log(c.gray(`  ${RATIO_NAMES[ratio] || 'custom ratio'}\n`));

  console.log(c.bold('  type'));
  for (const t of type) {
    const flag = t.step === 0 ? c.green(' ← body') : '';
    console.log(
      `    ${t.name.padEnd(6)} ${String(t.px).padStart(7)}px  ${String(t.rem).padStart(8)}rem` +
      `  ${c.gray(`lh ${t.leading}  ls ${t.tracking}`)}${flag}`
    );
    if (t.fluid) console.log(`           ${c.cyan(t.fluid)}`);
  }

  console.log(`\n${c.bold('  space')} ${c.gray('(4px base)')}`);
  const cols = space.map((s) => `${s.name}:${s.px}`);
  for (let i = 0; i < cols.length; i += 8) {
    console.log(`    ${cols.slice(i, i + 8).map((x) => x.padEnd(9)).join('')}`);
  }

  const jump = round(type.find((t) => t.step === 1).px - base, 2);
  console.log(`\n  ${c.cyan('checks')}`);
  console.log(`    base → next step jump: ${jump}px ${jump < 3 ? c.red('too small — hierarchy will not read') : c.green('ok')}`);
  console.log(`    ${c.gray('prose measure 60-75ch · display measure 20-40ch · body stays fixed, not fluid')}`);
  console.log(c.dim(`\n  Add --css, --tailwind or --json to emit tokens. --fluid for clamp() display sizes.\n`));
}

/* ----------------------------------------------------------------- helpers */

function sp(name) { return ' '.repeat(Math.max(1, 10 - String(name).length)); }
function round(n, d = 2) { return Math.round(n * 10 ** d) / 10 ** d; }
function num(v, dflt) { const n = Number(v); return Number.isFinite(n) && n > 0 ? n : dflt; }
function int(v, dflt, lo, hi) { const n = Number(v); return Number.isFinite(n) ? Math.min(hi, Math.max(lo, Math.round(n))) : dflt; }
