#!/usr/bin/env node
/**
 * overhaul-ui — tokens
 *
 * Emits a complete token file from a single brand colour: tinted neutral ramp,
 * accent ramp, semantic roles for both themes, type scale, space, radius,
 * shadow and motion.
 *
 *   node scripts/tokens.mjs --brand="#2C6E49"
 *   node scripts/tokens.mjs --brand="#2C6E49" --format=tailwind
 *   node scripts/tokens.mjs --brand="#2C6E49" --format=json --ratio=1.333
 *   node scripts/tokens.mjs --brand="#2C6E49" --out=src/styles/tokens.css
 *
 * Options
 *   --brand=<colour>   required. hex, rgb() or oklch()
 *   --hue=<deg>        neutral hue override (defaults to the brand hue)
 *   --ratio=<n>        type scale ratio (default 1.25)
 *   --base=<px>        body size (default 16)
 *   --format=css|tailwind|json|ts
 *   --out=<file>       write instead of printing
 */

import fs from 'node:fs';
import path from 'node:path';
import { parseArgs, c } from './lib/util.mjs';
import { parseColor, rgbToOklch, oklchToRgb, clampChroma, toHex, fmtOklch, contrastRatio } from './lib/color.mjs';

const args = parseArgs();
if (!args.brand) {
  console.log(`
${c.bold('overhaul-ui tokens')} — a full token set from one brand colour

  node scripts/tokens.mjs --brand="#2C6E49" [--format=css|tailwind|json|ts]
                          [--hue=<deg>] [--ratio=1.25] [--base=16] [--out=<file>]
`);
  process.exit(2);
}

let seed;
try {
  const rgb = parseColor(String(args.brand));
  seed = rgbToOklch(rgb.r, rgb.g, rgb.b);
} catch (err) {
  console.error(`${c.red('error')} ${err.message}`);
  process.exit(2);
}

const nHue = Number.isFinite(Number(args.hue)) ? Number(args.hue) : Math.round(seed.H * 10) / 10;
const base = Number(args.base) || 16;
const ratio = Number(args.ratio) || 1.25;
const format = String(args.format || 'css').toLowerCase();

/* ------------------------------------------------------------------- build */

const NEUTRAL_SPEC = [
  ['0', 0.990, 0.002], ['50', 0.975, 0.004], ['100', 0.945, 0.006],
  ['200', 0.895, 0.008], ['300', 0.815, 0.010], ['400', 0.685, 0.013],
  ['500', 0.565, 0.014], ['600', 0.470, 0.014], ['700', 0.385, 0.013],
  ['800', 0.285, 0.012], ['900', 0.205, 0.011], ['950', 0.155, 0.010],
  ['1000', 0.115, 0.009],
];

const ACCENT_SPEC = [
  ['50', 0.965], ['100', 0.930], ['200', 0.870], ['300', 0.790], ['400', 0.690],
  ['500', 0.620], ['600', 0.550], ['700', 0.470], ['800', 0.385], ['900', 0.300], ['950', 0.225],
];

const ramp = (spec, hue, chromaFn) =>
  spec.map(([name, L, C]) => {
    const target = C ?? chromaFn(L);
    const { C: cc } = clampChroma(L, target, hue);
    return { name, L, C: cc, H: hue, oklch: fmtOklch(L, cc, hue), hex: toHex(oklchToRgb(L, cc, hue)) };
  });

const chromaAt = (L) => {
  const peak = Math.max(seed.C, 0.06);
  const d = Math.abs(L - 0.58) / 0.58;
  return Math.max(0.015, peak * (0.28 + 0.72 * Math.max(0, 1 - Math.pow(d, 1.5))));
};

const neutrals = ramp(NEUTRAL_SPEC, nHue);
const accents = ramp(ACCENT_SPEC, seed.H, chromaAt);

const white = { r: 1, g: 1, b: 1 };
const nearBlack = oklchToRgb(0.165, 0.010, nHue);
// light theme: the LIGHTEST step that still clears 4.5:1 on white
// dark theme:  the DARKEST step that still clears 4.5:1 on near-black
const accentLight = accents.find((s) => contrastRatio(s.hex, white) >= 4.5) || accents[6];
const accentDark = [...accents].reverse().find((s) => contrastRatio(s.hex, nearBlack) >= 4.5) || accents[4];

const STATUS = {
  success: [0.550, 0.140, 150], warning: [0.720, 0.150, 75],
  danger: [0.550, 0.190, 25], info: [0.580, 0.140, 240],
};

const TYPE_NAMES = ['xs', 'sm', 'base', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl'];
const type = TYPE_NAMES.map((name, i) => {
  const step = i - 2;
  const px = Math.round(base * ratio ** step * 100) / 100;
  return { name, px, rem: Math.round((px / 16) * 10000) / 10000 };
});

const SPACE = [0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 20, 24, 32, 40];

/* ------------------------------------------------------------------ output */

const out =
  format === 'json' ? jsonOut() :
  format === 'ts' ? tsOut() :
  format === 'tailwind' ? tailwindOut() : cssOut();

if (args.out) {
  const file = path.resolve(String(args.out));
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, out.endsWith('\n') ? out : `${out}\n`, 'utf8');
  console.log(`${c.green('✓')} wrote ${c.bold(path.relative(process.cwd(), file))}  ${c.gray(`${format} · brand ${toHex(parseColor(String(args.brand)))} · neutral hue ${nHue}`)}`);
  console.log(c.dim('  Next: import it at the root, then verify with scripts/contrast.mjs --matrix'));
} else {
  console.log(out);
}

function cssOut() {
  const L = [];
  L.push('/* ---------------------------------------------------------------');
  L.push(' * design tokens — generated by overhaul-ui');
  L.push(` * brand ${toHex(parseColor(String(args.brand)))} · neutral hue ${nHue} · type ratio ${ratio}`);
  L.push(' * Architecture: primitive -> semantic -> component.');
  L.push(' * Components reference SEMANTIC tokens only, never a ramp step.');
  L.push(' * --------------------------------------------------------------- */');
  L.push('');
  L.push(':root {');
  L.push('  color-scheme: light;');
  L.push('');
  L.push('  /* primitives — neutrals, tinted with the brand hue */');
  neutrals.forEach((s) => L.push(`  --n-${s.name}: ${s.oklch};`.padEnd(44) + `/* ${s.hex} */`));
  L.push('');
  L.push('  /* primitives — accent */');
  accents.forEach((s) => L.push(`  --a-${s.name}: ${s.oklch};`.padEnd(44) + `/* ${s.hex} */`));
  L.push('');
  L.push('  /* primitives — status */');
  for (const [k, [l, cc, h]] of Object.entries(STATUS)) {
    L.push(`  --${k}-base: ${fmtOklch(l, cc, h)};`);
  }
  L.push('');
  L.push('  /* semantic — light theme */');
  L.push('  --bg: var(--n-0);');
  L.push('  --bg-subtle: var(--n-50);');
  L.push('  --bg-inset: var(--n-100);');
  L.push('  --bg-elevated: var(--n-0);');
  L.push(`  --bg-overlay: oklch(0.155 0.010 ${nHue} / 0.55);`);
  L.push('  --fg: var(--n-950);');
  L.push('  --fg-muted: var(--n-600);');
  L.push('  --fg-subtle: var(--n-500);');
  L.push('  --fg-on-accent: var(--n-0);');
  L.push('  --border: var(--n-200);');
  L.push('  --border-strong: var(--n-300);');
  L.push(`  --accent: var(--a-${accentLight.name});`);
  L.push(`  --accent-hover: var(--a-${bump(accentLight.name, 1)});`);
  L.push(`  --accent-active: var(--a-${bump(accentLight.name, 2)});`);
  L.push('  --accent-subtle: var(--a-50);');
  L.push(`  --ring: var(--a-${accentLight.name});`);
  for (const k of Object.keys(STATUS)) L.push(`  --${k}: var(--${k}-base);`);
  L.push('');
  L.push(`  /* type — base ${base}px, ratio ${ratio} */`);
  type.forEach((t) => L.push(`  --text-${t.name}: ${t.rem}rem;`.padEnd(30) + `/* ${t.px}px */`));
  L.push('  --text-display: clamp(2.4375rem, 1.2rem + 5.6vw, 4.75rem);');
  L.push('  --leading-tight: 1.1;  --leading-snug: 1.35;  --leading-normal: 1.55;');
  L.push('  --tracking-tight: -0.02em;  --tracking-wide: 0.08em;');
  L.push('  --measure-prose: 68ch;');
  L.push('');
  L.push('  /* space — 4px base */');
  SPACE.forEach((n) => L.push(`  --space-${n}: ${n === 0 ? '0' : `${n * 4 / 16}rem`};`));
  L.push('  --gutter: clamp(1rem, 4vw, 2.5rem);');
  L.push('  --section-y: clamp(4rem, 8vw, 10rem);');
  L.push('');
  L.push('  /* geometry */');
  L.push('  --radius-sm: 0.375rem; --radius-md: 0.5rem; --radius-lg: 0.75rem;');
  L.push('  --radius-xl: 1rem; --radius-full: 9999px;');
  L.push(`  --shadow-sm: 0 1px 2px oklch(0.2 0.02 ${nHue} / 0.06), 0 2px 6px oklch(0.2 0.02 ${nHue} / 0.05);`);
  L.push(`  --shadow-md: 0 2px 4px oklch(0.2 0.02 ${nHue} / 0.06), 0 8px 20px oklch(0.2 0.02 ${nHue} / 0.07);`);
  L.push(`  --shadow-lg: 0 4px 8px oklch(0.2 0.02 ${nHue} / 0.07), 0 20px 44px oklch(0.2 0.02 ${nHue} / 0.10);`);
  L.push('');
  L.push('  /* motion */');
  L.push('  --dur-1: 100ms; --dur-2: 150ms; --dur-3: 200ms; --dur-4: 300ms; --dur-5: 400ms;');
  L.push('  --ease-out: cubic-bezier(0.23, 1, 0.32, 1);');
  L.push('  --ease-in-out: cubic-bezier(0.77, 0, 0.175, 1);');
  L.push('  --ease-drawer: cubic-bezier(0.32, 0.72, 0, 1);');
  L.push('');
  L.push('  /* layers */');
  L.push('  --z-sticky: 20; --z-header: 40; --z-modal: 60; --z-toast: 80; --z-tooltip: 90;');
  L.push('}');
  L.push('');
  L.push('/* dark theme — overrides semantics only. Elevation goes LIGHTER. */');
  L.push('[data-theme="dark"] {');
  L.push('  color-scheme: dark;');
  L.push('  --bg: var(--n-1000);');
  L.push('  --bg-subtle: var(--n-900);');
  L.push('  --bg-inset: var(--n-1000);');
  L.push('  --bg-elevated: var(--n-800);');
  L.push(`  --bg-overlay: oklch(0.08 0.008 ${nHue} / 0.65);`);
  L.push('  --fg: var(--n-50);');
  L.push('  --fg-muted: var(--n-400);');
  L.push('  --fg-subtle: var(--n-500);');
  L.push('  --border: var(--n-800);');
  L.push('  --border-strong: var(--n-700);');
  L.push(`  --accent: var(--a-${accentDark.name});`);
  L.push(`  --accent-hover: var(--a-${bump(accentDark.name, -1)});`);
  L.push('  --accent-subtle: var(--a-950);');
  L.push('  --fg-on-accent: var(--n-1000);');
  L.push(`  --ring: var(--a-${accentDark.name});`);
  L.push('}');
  return L.join('\n');
}

function tailwindOut() {
  const L = ['@import "tailwindcss";', '', '/* generated by overhaul-ui tokens */', '@theme {'];
  neutrals.forEach((s) => L.push(`  --color-n-${s.name}: ${s.oklch};`));
  L.push('');
  accents.forEach((s) => L.push(`  --color-accent-${s.name}: ${s.oklch};`));
  L.push('');
  for (const [k, [l, cc, h]] of Object.entries(STATUS)) L.push(`  --color-${k}: ${fmtOklch(l, cc, h)};`);
  L.push('');
  type.forEach((t) => L.push(`  --text-${t.name}: ${t.rem}rem;`));
  L.push('');
  SPACE.forEach((n) => L.push(`  --spacing-${n}: ${n === 0 ? '0' : `${n * 4 / 16}rem`};`));
  L.push('');
  L.push('  --radius-sm: 0.375rem;');
  L.push('  --radius-md: 0.5rem;');
  L.push('  --radius-lg: 0.75rem;');
  L.push('  --ease-out: cubic-bezier(0.23, 1, 0.32, 1);');
  L.push('  --ease-in-out: cubic-bezier(0.77, 0, 0.175, 1);');
  L.push('}');
  L.push('');
  L.push('/* Semantic roles still belong in :root / [data-theme] so they can be');
  L.push('   swapped at runtime. Generate them with --format=css. */');
  return L.join('\n');
}

function jsonOut() {
  return JSON.stringify({
    tool: 'overhaul-ui/tokens',
    seed: { brand: toHex(parseColor(String(args.brand))), neutralHue: nHue, typeRatio: ratio, base },
    primitive: {
      neutral: Object.fromEntries(neutrals.map((s) => [s.name, s.oklch])),
      accent: Object.fromEntries(accents.map((s) => [s.name, s.oklch])),
      status: Object.fromEntries(Object.entries(STATUS).map(([k, [l, cc, h]]) => [k, fmtOklch(l, cc, h)])),
    },
    semantic: {
      light: {
        bg: 'n-0', 'bg-subtle': 'n-50', 'bg-elevated': 'n-0', fg: 'n-950',
        'fg-muted': 'n-600', border: 'n-200', accent: `a-${accentLight.name}`,
      },
      dark: {
        bg: 'n-1000', 'bg-subtle': 'n-900', 'bg-elevated': 'n-800', fg: 'n-50',
        'fg-muted': 'n-400', border: 'n-800', accent: `a-${accentDark.name}`,
      },
    },
    type: Object.fromEntries(type.map((t) => [t.name, `${t.rem}rem`])),
    space: Object.fromEntries(SPACE.map((n) => [String(n), n === 0 ? '0' : `${n * 4 / 16}rem`])),
    radius: { sm: '0.375rem', md: '0.5rem', lg: '0.75rem', xl: '1rem', full: '9999px' },
    motion: {
      duration: { 1: '100ms', 2: '150ms', 3: '200ms', 4: '300ms', 5: '400ms' },
      easing: {
        out: 'cubic-bezier(0.23, 1, 0.32, 1)',
        inOut: 'cubic-bezier(0.77, 0, 0.175, 1)',
        drawer: 'cubic-bezier(0.32, 0.72, 0, 1)',
      },
    },
  }, null, 2);
}

function tsOut() {
  const hexMap = (list) => `{\n${list.map((s) => `    "${s.name}": "${s.hex}",`).join('\n')}\n  }`;
  return `// generated by overhaul-ui tokens — React Native / Expo
// No CSS variables on this platform: one typed object plus a useTheme() hook.

export const palette = {
  neutral: ${hexMap(neutrals)},
  accent: ${hexMap(accents)},
} as const;

export const light = {
  bg: palette.neutral["0"],
  bgSubtle: palette.neutral["50"],
  bgElevated: palette.neutral["0"],
  fg: palette.neutral["950"],
  fgMuted: palette.neutral["600"],
  border: palette.neutral["200"],
  accent: palette.accent["${accentLight.name}"],
} as const;

export const dark = {
  bg: palette.neutral["1000"],
  bgSubtle: palette.neutral["900"],
  bgElevated: palette.neutral["800"],
  fg: palette.neutral["50"],
  fgMuted: palette.neutral["400"],
  border: palette.neutral["800"],
  accent: palette.accent["${accentDark.name}"],
} as const;

export const space = [${SPACE.map((n) => n * 4).join(', ')}] as const;
export const radius = { sm: 6, md: 8, lg: 12, xl: 16, full: 9999 } as const;
export const text = { ${type.map((t) => `"${t.name}": ${Math.round(t.px)}`).join(', ')} } as const;
export const duration = { d1: 100, d2: 150, d3: 200, d4: 300, d5: 400 } as const;

export type Theme = typeof light;
`;
}

function bump(name, by) {
  const order = ACCENT_SPEC.map(([n]) => n);
  const i = order.indexOf(name);
  return order[Math.min(order.length - 1, Math.max(0, i + by))];
}
